### ISSUE TITLE
sendData crash when buffer size doesn't line up

### ISSUE THREAD

**Issue by xoorath** [anacierdem/ed64#18]
Sorry in advance if I don't have the most reproducible use case in the world, but hopefully I can provide both the issue and a solution...

I was repeatedly getting the error **RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds** at the end of my writes; the last print I would get was "**Writing at 7Mb/7.02978515625Mb**"

After looking at sendData I suspected using STATUS_UPDATE_AT as the third parameter in Buffer.from looked fishy, since we should have the exact required size available.

I locally modified Buffer.from to take size-offset, and provided that to the writeNext at the end of sendData as well.

Might be an issue specific to the version of node I'm using, or could be the exact sizes I'm using. I'm not a node expert, so just in case it's helpful I'm on 10.16.0.

**Comment by anacierdem** [comment]
This breaks sub 2meg uploads as well, nice catch.
